// See https://aka.ms/new-console-template for more information
using LeetCode._75Questions;
using LeetCode._75Questions.Interview;
using LeetCode._75Questions.Week1;
using LeetCode._75Questions.Week2;
using LeetCode._75Questions.Week3;
using LeetCode._75Questions.Week4;
using LeetCode._75Questions.Week5;
using LeetCode._75Questions.Week6;


//_1TwoSum.Test();
//_21MergeTwoSortedLists.Test();
//_121BestTimeToBuyAndSellStock.Test();
//_125ValidPalindrome.Test();
//_226InvertBinaryTree.Test();
//_242ValidAnagram.Test();
//_704BinarySearch.Test();
//_733FloodFill.Test();
//_10BalancedBinaryTree.Test();
//_141LinkedListCycle.Test();
//_383RansomNote.Test();
//_70ClimbingStairs.Test();
//_409LongestPalindrome.Test();
//_206ReverseLinkedList.Test();
//_169MajorityElement.Test();
//_67AddBinary.Test();
//_104MaximumDepthOfBinaryTree.Test();
//_543DiameterOfBinaryTree.Test();
//_53MaximumSubarray.Test();
//_57InsertInterval.Test();
//MaxSum.Test();
//_54201Matrix.Test();
//_3LongestSubstringWithoutRepeatingCharacters.DoAction();
//_153Sum.Test();
//_136Single_Number.Test();
//_287FindTheDuplicateNumber.Test();
//_137SingleNumberII.Test();
//_973KClosestPointsToOrigin.Test();
//_215KthLargestElementInAnArray.Test();
//_124BinaryTreeMaximumPathSum.Test();
//_198HouseRobber.Test();
//_102BinaryTreeLevelOrderTraversal.Test();
//_133CloneGraph.Test();
//_150EvaluateReversePolishNotation.Test();
//_207_Course_Schedule.Test();
//_994_Rotting_Oranges.test();
//_200_Number_of_Islands.test();
//_98_Validate_Binary_Search_Tree.Test();
//_238_Product_of_Array_Except_Self.Test();
//_322_Coin_Change.Test();
//_75_Sort_Colors.Test();
//_33_Search_in_Rotated_Sorted_Array.Test();
//_39_Combination_Sum.Test();
//_56_Merge_Intervals.Test();
//_46_Permutations.Test();
//_981_Time_Based_Key_Value_Store.Test();
//Test1.Test();
//Test2.Test();
//KBTG.Test();
//_236_Lowest_Common_Ancestor_of_a_Binary_Tree.Test();
//_721__Accounts_Merge.Test();
//_139_Word_Break.Test();
//_54_Spiral_Matrix.Test();
//_62_Unique_Paths.Test();
//_199_Binary_Tree_Right_Side_View.Test();
_8_String_to_Integer__atoi_.Test();

//Console.WriteLine(4*3*2*1);
